name: Backend
on:
  push:
    branches:
      - main
    paths:
      - back/**
      - .github/workflows/backend.yml
  pull_request:
    branches:
      - main
    paths:
      - back/**
      - .github/workflows/backend.yml

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: back

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "back-ci"
        workspaces: "back -> target"
    - name: Check formatting
      run: cargo fmt --check

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install libjxl
      run: |
        sudo apt-get update
        sudo apt install libtcmalloc-minimal4 libhwy-dev
        curl -L -o package.tar.gz https://github.com/libjxl/libjxl/releases/download/v0.10.2/jxl-debs-amd64-ubuntu-22.04-v0.10.2.tar.gz
        tar -xvf package.tar.gz
        sudo dpkg -i libjxl_0.10.2_amd64.deb jxl_0.10.2_amd64.deb libjxl-dev_0.10.2_amd64.deb


    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "back-ci"
        workspaces: "back -> target"
    - name: Run clippy
      run: cargo clippy -- -Dwarnings

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: testing
          POSTGRES_PASSWORD: testing
          POSTGRES_DB: pictou-testing
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
    - uses: actions/checkout@v4

    - name: Install libjxl
      run: |
        sudo apt-get update
        sudo apt install libtcmalloc-minimal4 libhwy-dev
        curl -L -o package.tar.gz https://github.com/libjxl/libjxl/releases/download/v0.10.2/jxl-debs-amd64-ubuntu-22.04-v0.10.2.tar.gz
        tar -xvf package.tar.gz
        sudo dpkg -i libjxl_0.10.2_amd64.deb jxl_0.10.2_amd64.deb libjxl-dev_0.10.2_amd64.deb

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "back-ci"
        workspaces: "back -> target"

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run tests
      run: |
        cargo tarpaulin \
          --no-default-features --features testing-support \
          --timeout 120 --skip-clean --out xml -j 1

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        fail_ci_if_error: true
